version: "3.9"

services:
  pubmed_nlp_api:
    build: .
    container_name: pubmed_nlp_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    networks:
      - backend_network

networks:
  backend_network:
    external: true
